#!/bin/bash
#
# Written by: Shawn Dubbz

sudo echo ''
read -p '[?] Please choose a usage... (1: Last 50 entries / 2: Keep log open)  '  schoice
case $schoice in

	2)

		sudo tail -f /var/log/apache2/access.log

	;;
	
	1|*)

		sudo tail -50 /var/log/apache2/access.log

	;;

esac

echo ''
echo '[*] aplog Script completed, exiting...'
echo ''

	exit 0
