#!/bin/bash
#
# Written by Shawn Dubbz 
#
# Simple script to display currently active IP addresses
# on current machine
#

echo 'IP Address[s]:'
echo ''

	ifconfig | grep -v 127.0.0. | grep "inet" | grep -v inet6 | awk '{ print $2 }'

	exit 0
