#!/bin/bash
#
# Written by Shawn Dubbz
#
# Displays currently active UDP and TCP
# connections on current machine

sudo sleep .1
echo "Current UDP and TCP connections:"
echo ""

	sudo netstat -utapn | grep -v "Active"

echo ''
echo '[*] utapn Script completed, exiting...'
echo ''

	exit 0
